server:
  port: 8888

spring:
  application:
    name: cloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/microservice2025/cloud-config-server
          default-label: main